name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
      - name: checkout
        uses: actions/checkout@master # 将代码拷贝到虚机中

      - name: buildAndDeploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
          BRANCH: gh-pages # 存放产物的分支名称
          FOLDER: dist # 存放build后产物的目录
          BUILD_SCRIPT: npm install && npm run build # 执行的命令

      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:heartaotime/JK.git
          ssh_private_key: ${{ secrets.GITEE_PRIVATE_KEY }}

#      - name: Mirror the Github organization repos to Gitee.
#        uses: Yikun/hub-mirror-action@master
#        with:
#          src: github/heartaotime@foxmail.com
#          dst: gitee/heartaotime@foxmail.com
#          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#          dst_token: ${{ secrets.GITEE_TOKEN }}
#          account_type: user
