name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
      - name: checkout
        uses: actions/checkout@master # 将代码拷贝到虚机中

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: heartaotime/JK
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: dist/

      #      - name: buildAndDeploy
      #        uses: JamesIves/github-pages-deploy-action@master
      #        env:
      #          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
      #          BRANCH: gh-pages # 存放产物的分支名称
      #          FOLDER: dist # 存放build后产物的目录
      #          BUILD_SCRIPT: npm install && npm run build # 执行的命令

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:heartaotime/JK.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:heartaotime/JK.git"


      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: heartaotime
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: heartaotime/JK



#      - name: 'Mirror to gitee'
#        uses: pixta-dev/repository-mirroring-action@v1
#        with:
#          target_repo_url: git@gitee.com:heartaotime/JK.git
#          ssh_private_key: ${{ secrets.GITEE_PRIVATE_KEY }}




#      - name: Mirror the Github organization repos to Gitee.
#        uses: Yikun/hub-mirror-action@master
#        with:
#          src: github/heartaotime@foxmail.com
#          dst: gitee/heartaotime@foxmail.com
#          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#          dst_token: ${{ secrets.GITEE_TOKEN }}
#          account_type: user
